purepursuite:
  ros__parameters:
    long_max_speed: 2.0
    long_min_angle_diff_ACC: 0.2
    long_min_angle_diff_DEACC: 0.08
    long_switch_steps: 5.0

    lat_step_width: 10.0
    lat_x_start: 150.0
    lat_x_end: 210.0
    lat_x_distance: 280.0
    lat_wheel_base: 0.258
