/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bicycle_sim_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[7] = {5, 2, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[10] = 
  {2, 5, 0, 0, 0, 0, 1, 2,
  0, 1};
static const casadi_int casadi_s2[13] = 
  {5, 2, 0, 4, 8, 0, 1, 2,
  3, 0, 1, 2, 4};
static const casadi_int casadi_s3[11] = 
  {5, 2, 0, 3, 6, 0, 1, 2,
  0, 1, 2};
static const casadi_int casadi_s4[3] = {5, 1, 1};
static const casadi_int casadi_s5[3] = {5, 5, 1};
static const casadi_int casadi_s6[3] = {5, 2, 1};
static const casadi_int casadi_s7[3] = {2, 1, 1};
static const casadi_int casadi_s8[3] = {0, 1, 1};
static const casadi_int casadi_s9[23] = 
  {5, 5, 0, 3, 6, 9, 12, 15,
  0, 1, 2, 0, 1, 2, 0, 1,
  2, 0, 1, 2, 0, 1, 2};

static const casadi_real casadi_zeros[25] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0., 0., 0., 0.,
  0.};

/* bicycle_sim_expl_vde_forw:(i0[5],i1[5x5],i2[5x2],i3[2],i4[0])->(o0[5],o1[5x5,15nz],o2[5x2,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, w00, w01, w02, w03, w04, w05, w06, w13, w14, w15, w16;
  casadi_real w17, *w18=w+67, *w20=w+69, *w21=w+71, *w22=w+73, *w24=w+91, *w25=w+94, *w26=w+97, *w27=w+103;
  const casadi_real *cs, *wr07, *wr08, *wr09, *wr10, *wr11, *wr12, *wr23;
  /* #0: @0 = input[0][3] */
  w00 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w01 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w02 = cos( w01 );
  /* #3: @3 = (@0*@2) */
  w03  = (w00*w02);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w03;
  /* #5: @1 = sin(@1) */
  w01 = sin( w01 );
  /* #6: @3 = (@0*@1) */
  w03  = (w00*w01);
  /* #7: output[0][1] = @3 */
  if (res[0]) res[0][1] = w03;
  /* #8: @3 = 0.258 */
  w03 = 2.5800000000000001e-01;
  /* #9: @3 = (@0/@3) */
  w03  = (w00/w03);
  /* #10: @4 = input[0][4] */
  w04 = arg[0] ? arg[0][4] : 0;
  /* #11: @5 = tan(@4) */
  w05 = tan( w04 );
  /* #12: @6 = (@3*@5) */
  w06  = (w03*w05);
  /* #13: output[0][2] = @6 */
  if (res[0]) res[0][2] = w06;
  /* #14: @6 = input[3][0] */
  w06 = arg[3] ? arg[3][0] : 0;
  /* #15: output[0][3] = @6 */
  if (res[0]) res[0][3] = w06;
  /* #16: @6 = input[3][1] */
  w06 = arg[3] ? arg[3][1] : 0;
  /* #17: output[0][4] = @6 */
  if (res[0]) res[0][4] = w06;
  /* #18: @7 = input[1][0] */
  wr07 = arg[1] ? arg[1] : casadi_zeros;
  /* #19: {@8, @9, @10, @11, @12} = horzsplit(@7) */
  wr08 = wr07;
  wr09 = wr07+5;
  wr10 = wr07+10;
  wr11 = wr07+15;
  wr12 = wr07+20;
  /* #20: {NULL, NULL, @6, @13, @14} = vertsplit(@8) */
  w06 = wr08[2];
  w13 = wr08[3];
  w14 = wr08[4];
  /* #21: @15 = (@2*@13) */
  w15  = (w02*w13);
  /* #22: @16 = (@1*@6) */
  w16  = (w01*w06);
  /* #23: @16 = (@0*@16) */
  w16  = (w00*w16);
  /* #24: @15 = (@15-@16) */
  w15 -= w16;
  /* #25: output[1][0] = @15 */
  if (res[1]) res[1][0] = w15;
  /* #26: @15 = (@1*@13) */
  w15  = (w01*w13);
  /* #27: @6 = (@2*@6) */
  w06  = (w02*w06);
  /* #28: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #29: @15 = (@15+@6) */
  w15 += w06;
  /* #30: output[1][1] = @15 */
  if (res[1]) res[1][1] = w15;
  /* #31: @15 = 3.87597 */
  w15 = 3.8759689922480618e+00;
  /* #32: @13 = (@15*@13) */
  w13  = (w15*w13);
  /* #33: @13 = (@5*@13) */
  w13  = (w05*w13);
  /* #34: @4 = cos(@4) */
  w04 = cos( w04 );
  /* #35: @4 = sq(@4) */
  w04 = casadi_sq( w04 );
  /* #36: @14 = (@14/@4) */
  w14 /= w04;
  /* #37: @14 = (@3*@14) */
  w14  = (w03*w14);
  /* #38: @13 = (@13+@14) */
  w13 += w14;
  /* #39: output[1][2] = @13 */
  if (res[1]) res[1][2] = w13;
  /* #40: {NULL, NULL, @13, @14, @6} = vertsplit(@9) */
  w13 = wr09[2];
  w14 = wr09[3];
  w06 = wr09[4];
  /* #41: @16 = (@2*@14) */
  w16  = (w02*w14);
  /* #42: @17 = (@1*@13) */
  w17  = (w01*w13);
  /* #43: @17 = (@0*@17) */
  w17  = (w00*w17);
  /* #44: @16 = (@16-@17) */
  w16 -= w17;
  /* #45: output[1][3] = @16 */
  if (res[1]) res[1][3] = w16;
  /* #46: @16 = (@1*@14) */
  w16  = (w01*w14);
  /* #47: @13 = (@2*@13) */
  w13  = (w02*w13);
  /* #48: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #49: @16 = (@16+@13) */
  w16 += w13;
  /* #50: output[1][4] = @16 */
  if (res[1]) res[1][4] = w16;
  /* #51: @14 = (@15*@14) */
  w14  = (w15*w14);
  /* #52: @14 = (@5*@14) */
  w14  = (w05*w14);
  /* #53: @6 = (@6/@4) */
  w06 /= w04;
  /* #54: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #55: @14 = (@14+@6) */
  w14 += w06;
  /* #56: output[1][5] = @14 */
  if (res[1]) res[1][5] = w14;
  /* #57: {NULL, NULL, @14, @6, @16} = vertsplit(@10) */
  w14 = wr10[2];
  w06 = wr10[3];
  w16 = wr10[4];
  /* #58: @13 = (@2*@6) */
  w13  = (w02*w06);
  /* #59: @17 = (@1*@14) */
  w17  = (w01*w14);
  /* #60: @17 = (@0*@17) */
  w17  = (w00*w17);
  /* #61: @13 = (@13-@17) */
  w13 -= w17;
  /* #62: output[1][6] = @13 */
  if (res[1]) res[1][6] = w13;
  /* #63: @13 = (@1*@6) */
  w13  = (w01*w06);
  /* #64: @14 = (@2*@14) */
  w14  = (w02*w14);
  /* #65: @14 = (@0*@14) */
  w14  = (w00*w14);
  /* #66: @13 = (@13+@14) */
  w13 += w14;
  /* #67: output[1][7] = @13 */
  if (res[1]) res[1][7] = w13;
  /* #68: @6 = (@15*@6) */
  w06  = (w15*w06);
  /* #69: @6 = (@5*@6) */
  w06  = (w05*w06);
  /* #70: @16 = (@16/@4) */
  w16 /= w04;
  /* #71: @16 = (@3*@16) */
  w16  = (w03*w16);
  /* #72: @6 = (@6+@16) */
  w06 += w16;
  /* #73: output[1][8] = @6 */
  if (res[1]) res[1][8] = w06;
  /* #74: {NULL, NULL, @6, @16, @13} = vertsplit(@11) */
  w06 = wr11[2];
  w16 = wr11[3];
  w13 = wr11[4];
  /* #75: @14 = (@2*@16) */
  w14  = (w02*w16);
  /* #76: @17 = (@1*@6) */
  w17  = (w01*w06);
  /* #77: @17 = (@0*@17) */
  w17  = (w00*w17);
  /* #78: @14 = (@14-@17) */
  w14 -= w17;
  /* #79: output[1][9] = @14 */
  if (res[1]) res[1][9] = w14;
  /* #80: @14 = (@1*@16) */
  w14  = (w01*w16);
  /* #81: @6 = (@2*@6) */
  w06  = (w02*w06);
  /* #82: @6 = (@0*@6) */
  w06  = (w00*w06);
  /* #83: @14 = (@14+@6) */
  w14 += w06;
  /* #84: output[1][10] = @14 */
  if (res[1]) res[1][10] = w14;
  /* #85: @16 = (@15*@16) */
  w16  = (w15*w16);
  /* #86: @16 = (@5*@16) */
  w16  = (w05*w16);
  /* #87: @13 = (@13/@4) */
  w13 /= w04;
  /* #88: @13 = (@3*@13) */
  w13  = (w03*w13);
  /* #89: @16 = (@16+@13) */
  w16 += w13;
  /* #90: output[1][11] = @16 */
  if (res[1]) res[1][11] = w16;
  /* #91: {NULL, NULL, @16, @13, @14} = vertsplit(@12) */
  w16 = wr12[2];
  w13 = wr12[3];
  w14 = wr12[4];
  /* #92: @6 = (@2*@13) */
  w06  = (w02*w13);
  /* #93: @17 = (@1*@16) */
  w17  = (w01*w16);
  /* #94: @17 = (@0*@17) */
  w17  = (w00*w17);
  /* #95: @6 = (@6-@17) */
  w06 -= w17;
  /* #96: output[1][12] = @6 */
  if (res[1]) res[1][12] = w06;
  /* #97: @6 = (@1*@13) */
  w06  = (w01*w13);
  /* #98: @16 = (@2*@16) */
  w16  = (w02*w16);
  /* #99: @16 = (@0*@16) */
  w16  = (w00*w16);
  /* #100: @6 = (@6+@16) */
  w06 += w16;
  /* #101: output[1][13] = @6 */
  if (res[1]) res[1][13] = w06;
  /* #102: @13 = (@15*@13) */
  w13  = (w15*w13);
  /* #103: @13 = (@5*@13) */
  w13  = (w05*w13);
  /* #104: @14 = (@14/@4) */
  w14 /= w04;
  /* #105: @14 = (@3*@14) */
  w14  = (w03*w14);
  /* #106: @13 = (@13+@14) */
  w13 += w14;
  /* #107: output[1][14] = @13 */
  if (res[1]) res[1][14] = w13;
  /* #108: @18 = zeros(2x5,2nz) */
  casadi_clear(w18, 2);
  /* #109: @19 = 00 */
  /* #110: @20 = ones(2x1) */
  casadi_fill(w20, 2, 1.);
  /* #111: {@13, @14} = vertsplit(@20) */
  w13 = w20[0];
  w14 = w20[1];
  /* #112: @20 = vertcat(@19, @19, @19, @13, @14) */
  rr=w20;
  *rr++ = w13;
  *rr++ = w14;
  /* #113: @21 = @20[:2] */
  for (rr=w21, cs=w20+0; cs!=w20+2; cs+=1) *rr++ = *cs;
  /* #114: (@18[:2] = @21) */
  for (rr=w18+0, cs=w21; rr!=w18+2; rr+=1) *rr = *cs++;
  /* #115: @21 = @18' */
  casadi_trans(w18,casadi_s1, w21, casadi_s0, iw);
  /* #116: @22 = project(@21) */
  casadi_project(w21, casadi_s0, w22, casadi_s2, w);
  /* #117: @23 = input[2][0] */
  wr23 = arg[2] ? arg[2] : casadi_zeros;
  /* #118: {@12, @11} = horzsplit(@23) */
  wr12 = wr23;
  wr11 = wr23+5;
  /* #119: {NULL, NULL, @13, @14, @6} = vertsplit(@12) */
  w13 = wr12[2];
  w14 = wr12[3];
  w06 = wr12[4];
  /* #120: @16 = (@2*@14) */
  w16  = (w02*w14);
  /* #121: @17 = (@1*@13) */
  w17  = (w01*w13);
  /* #122: @17 = (@0*@17) */
  w17  = (w00*w17);
  /* #123: @16 = (@16-@17) */
  w16 -= w17;
  /* #124: @17 = (@1*@14) */
  w17  = (w01*w14);
  /* #125: @13 = (@2*@13) */
  w13  = (w02*w13);
  /* #126: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #127: @17 = (@17+@13) */
  w17 += w13;
  /* #128: @14 = (@15*@14) */
  w14  = (w15*w14);
  /* #129: @14 = (@5*@14) */
  w14  = (w05*w14);
  /* #130: @6 = (@6/@4) */
  w06 /= w04;
  /* #131: @6 = (@3*@6) */
  w06  = (w03*w06);
  /* #132: @14 = (@14+@6) */
  w14 += w06;
  /* #133: @24 = vertcat(@16, @17, @14, @19, @19) */
  rr=w24;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w14;
  /* #134: {NULL, NULL, @16, @17, @14} = vertsplit(@11) */
  w16 = wr11[2];
  w17 = wr11[3];
  w14 = wr11[4];
  /* #135: @6 = (@2*@17) */
  w06  = (w02*w17);
  /* #136: @13 = (@1*@16) */
  w13  = (w01*w16);
  /* #137: @13 = (@0*@13) */
  w13  = (w00*w13);
  /* #138: @6 = (@6-@13) */
  w06 -= w13;
  /* #139: @1 = (@1*@17) */
  w01 *= w17;
  /* #140: @2 = (@2*@16) */
  w02 *= w16;
  /* #141: @0 = (@0*@2) */
  w00 *= w02;
  /* #142: @1 = (@1+@0) */
  w01 += w00;
  /* #143: @15 = (@15*@17) */
  w15 *= w17;
  /* #144: @5 = (@5*@15) */
  w05 *= w15;
  /* #145: @14 = (@14/@4) */
  w14 /= w04;
  /* #146: @3 = (@3*@14) */
  w03 *= w14;
  /* #147: @5 = (@5+@3) */
  w05 += w03;
  /* #148: @25 = vertcat(@6, @1, @5, @19, @19) */
  rr=w25;
  *rr++ = w06;
  *rr++ = w01;
  *rr++ = w05;
  /* #149: @26 = horzcat(@24, @25) */
  rr=w26;
  for (i=0, cs=w24; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  /* #150: @27 = project(@26) */
  casadi_project(w26, casadi_s3, w27, casadi_s2, w);
  /* #151: @22 = (@22+@27) */
  for (i=0, rr=w22, cs=w27; i<8; ++i) (*rr++) += (*cs++);
  /* #152: output[2][0] = @22 */
  casadi_copy(w22, 8, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_sim_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bicycle_sim_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_sim_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_sim_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bicycle_sim_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_sim_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bicycle_sim_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void bicycle_sim_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bicycle_sim_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int bicycle_sim_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real bicycle_sim_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_sim_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_sim_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_sim_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_sim_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bicycle_sim_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 3;
  if (sz_w) *sz_w = 111;
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_sim_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 3*sizeof(casadi_int);
  if (sz_w) *sz_w = 111*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
