button_launch:
  ros__parameters:
    first: controller_type:=purepursuit start_box:=true obstacle_detection_type:=none driving_speed:=slow driving_lane:=inner
    second: controller_type:=purepursuit start_box:=true obstacle_detection_type:=none driving_speed:=fast driving_lane:=inner
    third: controller_type:=purepursuit start_box:=true obstacle_detection_type:=none driving_speed:=risky driving_lane:=inner