uc_com:
  ros__parameters:

    min_speed_ucb: 400.0

    min_angle_ucb: -175.0
    max_angle_ucb: 225.0
    max_speed_ucb: 1000.0
    hysterese_distance: 0.0
    hysterese_offset: 0.03
    min_angle_diff: 0.01
    switch_steps: 6.0
    steering_speed_factor: 800.0
    avoid_crash: false
