/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bicycle_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_fmin CASADI_PREFIX(fmin)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

casadi_real casadi_fmin(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x<y ? x : y;
#else
  return fmin(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {8, 1, 1};

static const casadi_real casadi_zeros[8] = {0., 0., 0., 0., 0., 0., 0., 0.};

/* bicycle_model_expl_ode_fun:(i0[7],i1[2],i2[8])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w00, w01, w02, w03, w05, w06, w07, w08, w09, w10, w11, w12;
  casadi_real w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24;
  casadi_real w25, w26;
  const casadi_real *wr04;
  /* #0: @0 = input[0][3] */
  w00 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w01 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w02 = cos( w01 );
  /* #3: @2 = (@0*@2) */
  w02  = (w00*w02);
  /* #4: @3 = 1 */
  w03 = 1.;
  /* #5: @4 = input[2][0] */
  wr04 = arg[2] ? arg[2] : casadi_zeros;
  /* #6: @5 = @4[2] */
  w05 = wr04[2];
  /* #7: @6 = 3 */
  w06 = 3.;
  /* #8: @7 = 0 */
  w07 = 0.;
  /* #9: @8 = input[0][0] */
  w08 = arg[0] ? arg[0][0] : 0;
  /* #10: @9 = 0.5 */
  w09 = 5.0000000000000000e-01;
  /* #11: @10 = @4[6] */
  w10 = wr04[6];
  /* #12: @11 = @4[0] */
  w11 = wr04[0];
  /* #13: @12 = (@10-@11) */
  w12  = (w10-w11);
  /* #14: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #15: @13 = @4[7] */
  w13 = wr04[7];
  /* #16: @14 = @4[1] */
  w14 = wr04[1];
  /* #17: @15 = (@13-@14) */
  w15  = (w13-w14);
  /* #18: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #19: @12 = (@12+@15) */
  w12 += w15;
  /* #20: @12 = sqrt(@12) */
  w12 = sqrt( w12 );
  /* #21: @15 = (@5-@11) */
  w15  = (w05-w11);
  /* #22: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #23: @16 = @4[3] */
  w16 = wr04[3];
  /* #24: @17 = (@16-@14) */
  w17  = (w16-w14);
  /* #25: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #26: @15 = (@15+@17) */
  w15 += w17;
  /* #27: @15 = sqrt(@15) */
  w15 = sqrt( w15 );
  /* #28: @12 = (@12+@15) */
  w12 += w15;
  /* #29: @15 = @4[4] */
  w15 = wr04[4];
  /* #30: @17 = (@15-@5) */
  w17  = (w15-w05);
  /* #31: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #32: @18 = @4[5] */
  w18 = wr04[5];
  /* #33: @19 = (@18-@16) */
  w19  = (w18-w16);
  /* #34: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #35: @17 = (@17+@19) */
  w17 += w19;
  /* #36: @17 = sqrt(@17) */
  w17 = sqrt( w17 );
  /* #37: @12 = (@12+@17) */
  w12 += w17;
  /* #38: @17 = (@10-@15) */
  w17  = (w10-w15);
  /* #39: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #40: @19 = (@13-@18) */
  w19  = (w13-w18);
  /* #41: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #42: @17 = (@17+@19) */
  w17 += w19;
  /* #43: @17 = sqrt(@17) */
  w17 = sqrt( w17 );
  /* #44: @12 = (@12+@17) */
  w12 += w17;
  /* #45: @9 = (@9*@12) */
  w09 *= w12;
  /* #46: @8 = (@8/@9) */
  w08 /= w09;
  /* #47: @12 = fmax(@7,@8) */
  w12  = casadi_fmax(w07,w08);
  /* #48: @17 = fmin(@3,@12) */
  w17  = casadi_fmin(w03,w12);
  /* #49: @19 = (@3-@17) */
  w19  = (w03-w17);
  /* #50: @20 = sq(@19) */
  w20 = casadi_sq( w19 );
  /* #51: @20 = (@6*@20) */
  w20  = (w06*w20);
  /* #52: @21 = (@12<=@3) */
  w21  = (w12<=w03);
  /* #53: @12 = (@3<=@12) */
  w12  = (w03<=w12);
  /* #54: @12 = (@12+@21) */
  w12 += w21;
  /* #55: @21 = (@21/@12) */
  w21 /= w12;
  /* #56: @12 = (@7<=@8) */
  w12  = (w07<=w08);
  /* #57: @8 = (@8<=@7) */
  w08  = (w08<=w07);
  /* #58: @8 = (@8+@12) */
  w08 += w12;
  /* #59: @12 = (@12/@8) */
  w12 /= w08;
  /* #60: @12 = (@12/@9) */
  w12 /= w09;
  /* #61: @21 = (@21*@12) */
  w21 *= w12;
  /* #62: @20 = (@20*@21) */
  w20 *= w21;
  /* #63: @12 = (2.*@19) */
  w12 = (2.* w19 );
  /* #64: @12 = (@12*@21) */
  w12 *= w21;
  /* #65: @12 = (@6*@12) */
  w12  = (w06*w12);
  /* #66: @9 = (@17*@12) */
  w09  = (w17*w12);
  /* #67: @9 = (@20-@9) */
  w09  = (w20-w09);
  /* #68: @8 = (@5*@9) */
  w08  = (w05*w09);
  /* #69: @7 = (@11*@20) */
  w07  = (w11*w20);
  /* #70: @8 = (@8-@7) */
  w08 -= w07;
  /* #71: @19 = (@6*@19) */
  w19  = (w06*w19);
  /* #72: @7 = (2.*@17) */
  w07 = (2.* w17 );
  /* #73: @7 = (@7*@21) */
  w07 *= w21;
  /* #74: @22 = (@19*@7) */
  w22  = (w19*w07);
  /* #75: @23 = sq(@17) */
  w23 = casadi_sq( w17 );
  /* #76: @24 = (@6*@21) */
  w24  = (w06*w21);
  /* #77: @25 = (@23*@24) */
  w25  = (w23*w24);
  /* #78: @22 = (@22-@25) */
  w22 -= w25;
  /* #79: @25 = (@15*@22) */
  w25  = (w15*w22);
  /* #80: @8 = (@8+@25) */
  w08 += w25;
  /* #81: @23 = (@6*@23) */
  w23  = (w06*w23);
  /* #82: @23 = (@23*@21) */
  w23 *= w21;
  /* #83: @25 = (@10*@23) */
  w25  = (w10*w23);
  /* #84: @8 = (@8+@25) */
  w08 += w25;
  /* #85: @25 = (@12*@21) */
  w25  = (w12*w21);
  /* #86: @26 = (-@21) */
  w26 = (- w21 );
  /* #87: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #88: @26 = (@21*@26) */
  w26  = (w21*w26);
  /* #89: @26 = (@6*@26) */
  w26  = (w06*w26);
  /* #90: @17 = (@17*@26) */
  w17 *= w26;
  /* #91: @25 = (@25+@17) */
  w25 += w17;
  /* #92: @25 = (-@25) */
  w25 = (- w25 );
  /* #93: @12 = (@21*@12) */
  w12  = (w21*w12);
  /* #94: @25 = (@25-@12) */
  w25 -= w12;
  /* #95: @17 = (@16*@25) */
  w17  = (w16*w25);
  /* #96: @26 = (@14*@12) */
  w26  = (w14*w12);
  /* #97: @17 = (@17+@26) */
  w17 += w26;
  /* #98: @26 = (2.*@21) */
  w26 = (2.* w21 );
  /* #99: @26 = (@21*@26) */
  w26  = (w21*w26);
  /* #100: @19 = (@19*@26) */
  w19 *= w26;
  /* #101: @26 = (@7*@24) */
  w26  = (w07*w24);
  /* #102: @19 = (@19-@26) */
  w19 -= w26;
  /* #103: @24 = (@24*@7) */
  w24 *= w07;
  /* #104: @19 = (@19-@24) */
  w19 -= w24;
  /* #105: @24 = (@18*@19) */
  w24  = (w18*w19);
  /* #106: @17 = (@17+@24) */
  w17 += w24;
  /* #107: @6 = (@6*@7) */
  w06 *= w07;
  /* #108: @21 = (@21*@6) */
  w21 *= w06;
  /* #109: @6 = (@13*@21) */
  w06  = (w13*w21);
  /* #110: @17 = (@17+@6) */
  w17 += w06;
  /* #111: @17 = (@8*@17) */
  w17  = (w08*w17);
  /* #112: @16 = (@16*@9) */
  w16 *= w09;
  /* #113: @14 = (@14*@20) */
  w14 *= w20;
  /* #114: @16 = (@16-@14) */
  w16 -= w14;
  /* #115: @18 = (@18*@22) */
  w18 *= w22;
  /* #116: @16 = (@16+@18) */
  w16 += w18;
  /* #117: @13 = (@13*@23) */
  w13 *= w23;
  /* #118: @16 = (@16+@13) */
  w16 += w13;
  /* #119: @5 = (@5*@25) */
  w05 *= w25;
  /* #120: @11 = (@11*@12) */
  w11 *= w12;
  /* #121: @5 = (@5+@11) */
  w05 += w11;
  /* #122: @15 = (@15*@19) */
  w15 *= w19;
  /* #123: @5 = (@5+@15) */
  w05 += w15;
  /* #124: @10 = (@10*@21) */
  w10 *= w21;
  /* #125: @5 = (@5+@10) */
  w05 += w10;
  /* #126: @5 = (@16*@5) */
  w05  = (w16*w05);
  /* #127: @17 = (@17-@5) */
  w17 -= w05;
  /* #128: @5 = sq(@8) */
  w05 = casadi_sq( w08 );
  /* #129: @10 = sq(@16) */
  w10 = casadi_sq( w16 );
  /* #130: @5 = (@5+@10) */
  w05 += w10;
  /* #131: @10 = 1.5 */
  w10 = 1.5000000000000000e+00;
  /* #132: @5 = pow(@5,@10) */
  w05  = pow(w05,w10);
  /* #133: @17 = (@17/@5) */
  w17 /= w05;
  /* #134: @5 = input[0][1] */
  w05 = arg[0] ? arg[0][1] : 0;
  /* #135: @5 = (@17*@5) */
  w05  = (w17*w05);
  /* #136: @3 = (@3-@5) */
  w03 -= w05;
  /* #137: @2 = (@2/@3) */
  w02 /= w03;
  /* #138: output[0][0] = @2 */
  if (res[0]) res[0][0] = w02;
  /* #139: @3 = sin(@1) */
  w03 = sin( w01 );
  /* #140: @3 = (@0*@3) */
  w03  = (w00*w03);
  /* #141: output[0][1] = @3 */
  if (res[0]) res[0][1] = w03;
  /* #142: @3 = 0.258 */
  w03 = 2.5800000000000001e-01;
  /* #143: @3 = (@0/@3) */
  w03  = (w00/w03);
  /* #144: @5 = input[0][4] */
  w05 = arg[0] ? arg[0][4] : 0;
  /* #145: @5 = tan(@5) */
  w05 = tan( w05 );
  /* #146: @3 = (@3*@5) */
  w03 *= w05;
  /* #147: @17 = (@17*@2) */
  w17 *= w02;
  /* #148: @3 = (@3-@17) */
  w03 -= w17;
  /* #149: output[0][2] = @3 */
  if (res[0]) res[0][2] = w03;
  /* #150: @3 = input[1][0] */
  w03 = arg[1] ? arg[1][0] : 0;
  /* #151: output[0][3] = @3 */
  if (res[0]) res[0][3] = w03;
  /* #152: @3 = input[1][1] */
  w03 = arg[1] ? arg[1][1] : 0;
  /* #153: output[0][4] = @3 */
  if (res[0]) res[0][4] = w03;
  /* #154: @16 = atan2(@16,@8) */
  w16  = atan2(w16,w08);
  /* #155: @16 = (@16+@1) */
  w16 += w01;
  /* #156: @1 = cos(@16) */
  w01 = cos( w16 );
  /* #157: @1 = (@0*@1) */
  w01  = (w00*w01);
  /* #158: output[0][5] = @1 */
  if (res[0]) res[0][5] = w01;
  /* #159: @16 = sin(@16) */
  w16 = sin( w16 );
  /* #160: @0 = (@0*@16) */
  w00 *= w16;
  /* #161: output[0][6] = @0 */
  if (res[0]) res[0][6] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void bicycle_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int bicycle_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bicycle_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bicycle_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bicycle_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 34;
  return 0;
}

CASADI_SYMBOL_EXPORT int bicycle_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 34*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
