purepursuite:
  ros__parameters:
    long_max_speed: 1.6
    long_min_angle_diff_ACC: 0.2
    long_min_angle_diff_DEACC: 0.15
    long_switch_steps: 7.0

    lat_step_width: 10.0
    lat_x_start: 170.0
    lat_x_end: 280.0
    lat_x_distance: 300.0
    lat_wheel_base: 0.258


