uc_com:
  ros__parameters:

    min_speed_ucb: 700.0

    min_angle_ucb: -190.0
    max_angle_ucb: 235.0
    max_speed_ucb: 1000.0
    hysterese_distance: 0.0
    hysterese_offset: 0.03
    min_angle_diff: 0.01
    switch_steps: 2.0
    steering_speed_factor: 900.0
    avoid_crash: false
